### ISSUE TITLE
Bug report: Time missing

### ISSUE THREAD

**Issue by rocklobster42195** [klein0r/ioBroker.awtrix-light#68] opened 2023-09-15 07:50 UTC
### The problem

I have 8 apps running plus the Awtrix-light time app. Three of my apps are temporarily hidden. The display cycles through the apps, but the time is not displayed. If I turn the time app off and on again in the display settings, the time is displayed again. After a reboot, the time is displayed. The iobroker logo appears at some point, then the time is missing again.
Could it be that there is a problem after sorting my apps?

### Version of nodejs

18.17.1

### Version of ioBroker js-controller

5.0.12

### Version of Adapter

0.8.0

### Version of awtrix-light firmware

0.87

### Operating system running ioBroker

Ubuntu 20.04.6 LTS

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

### Additional information & file uploads

No errors in the log

**Comment by ME8800** [comment] 2023-09-16 13:59
I can confirm the bug, while the App deleting at restart and delete unknown Apps in the adapter settings is checked. I think the build-in clock app is declared as unknown since awtrixFW 0.8.7

**Comment by Ricox1975** [comment] 2023-09-19 16:32
here the same on FW 0.88

**Comment by klein0r** [comment] 2023-10-01 10:47
Native apps have been renamed - will be fixed in the next version.
See #71

**Closed by klein0r** 2023-10-01 10:47 UTC
Labels: bug
